# -*- coding: utf-8 -*-
"""20240904 hello-world

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sQJZlAYgWmDC5R48sEqrgZP-aavJbh4t
"""

print("Hello World!!")

print("Hello Python")

import pylab as py

x_deg = py. arange(-180, 180+1,)
x_rad = py.deg2rad(x_deg)
y=py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)





